apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: monitoring
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http-grafana
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
  - name: https-grafana
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: grafana-tls-secret
        kind: Secret
    allowedRoutes:
      namespaces:
        from: Same
