apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loki-test-route
  namespace: monitoring
spec:
  parentRefs:
  - name: default-gateway
    namespace: gateway-system
  hostnames:
  - loki-test.prakriti.website
  rules:
  - backendRefs:
    - name: service-a
      port: 8080
