spring.application.name=order-management
server.port=9090
server.address=0.0.0.0
PRODUCT_INVENTORY_API_HOST=http://localhost
PRODUCT_CATALOG_API_HOST=http://localhost
SHIPPING_HANDLING_API_HOST=http://localhost

# Database Configurations
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Actuator & Prometheus Metrics Configuration for Latency, Response Time, Throughput, Error Rates & Resource Usage
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=order-management
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.9,0.95,0.99
management.metrics.distribution.sla.http.server.requests=5ms,10ms,25ms,50ms,100ms,250ms,500ms,1s,2s,5s
management.metrics.enable.all=true
management.metrics.enable.process=true
management.metrics.enable.jvm=true
management.metrics.enable.system=true
management.metrics.enable.disk=true
management.metrics.web.server.request.autotime.enabled=true