mode: deployment

image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15

    batch:
      send_batch_size: 1000
      timeout: 1s
      send_batch_max_size: 1024

    # (Optional) Ensures service.name or k8s metadata is populated
    resourcedetection:
      detectors: [env, system]
      timeout: 2s

  exporters:
    otlphttp/loki:
      endpoint: "http://loki-gateway.monitoring.svc.cluster.local/otlp"
      compression: gzip
      tls:
        insecure: true
    otlp/tempo:
      endpoint: "tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true
    prometheusremotewrite:
      endpoint: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
      tls:
        insecure: true

  service:
    pipelines:
      logs:
        receivers: [otlp]
        processors: [memory_limiter, resourcedetection, batch]
        exporters: [otlphttp/loki]
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, resourcedetection, batch]
        exporters: [prometheusremotewrite]
      traces:
        receivers: [otlp]
        processors: [memory_limiter, resourcedetection, batch]
        exporters: [otlp/tempo]