apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
type: Opaque
stringData:
  slack-webhook-url: "http://localhost/dummy-slack-webhook"
  pagerduty-service-key: "YOUR_PAGERDUTY_INTEGRATION_KEY_HERE"
