apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: thanos-healthcheck
  namespace: monitoring
spec:
  default:
    config:
      httpHealthCheck:
        requestPath: /-/healthy
      type: HTTP
  targetRef:
    group: ""
    kind: Service
    name: thanos-query
