apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
data:
  fluent.conf: |-
    @include pods-kind-fluent.conf
    @include elastic-fluent.conf

  pods-kind-fluent.conf: |-
    <source>
      @type tail
      read_from_head true
      # 1. Change tag to allow Fluentd to append the file path automatically
      tag kubernetes.*
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      exclude_path ["/var/log/containers/fluent*"]
      <parse>
        @type regexp
        expression ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.[^Z]*Z)\s(?<stream>[^\s]+)\s(?<character>[^\s])\s(?<message>.*)$
        keep_time_key true
      </parse>
    </source>

    # 2. Tell the metadata filter to look at the dynamically generated tag paths
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
    </filter>

    # 3. GKE Bonus: Flatten the nested CRI 'message' string into a root object if it's JSON
    <filter kubernetes.**>
      @type parser
      key_name message
      reserve_data true
      remove_key_name_field true
      <parse>
        @type json
      </parse>
    </filter>

  elastic-fluent.conf: |-
    <match **>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'elasticsearch.elastic-kibana.svc.cluster.local'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      index_name fluentd-k8s
      suppress_type_name true
      include_timestamp true
      <buffer>
        @type memory
        flush_interval 5s
      </buffer>
    </match>