name: Build and Push Loki Test Apps

on:
  push:
    paths:
      - 'test/**'
      - '.github/workflows/loki-test-apps.yaml'
  workflow_dispatch:

env:
  GAR_LOCATION: us-central1
  PROJECT_ID: k8s-staging-252732

jobs:
  build-and-push:
    name: Build & Push ${{ matrix.service }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for requesting the OIDC JWT token
    strategy:
      fail-fast: false
      matrix:
        service: [service-a, service-b, service-c, service-d, service-e]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: 'projects/898698082979/locations/global/workloadIdentityPools/loki-test-pool/providers/github-provider'
          service_account: 'loki-test-pusher@k8s-staging-252732.iam.gserviceaccount.com'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Prepare Proto
        if: matrix.service == 'service-c' || matrix.service == 'service-d'
        run: cp -r test/proto test/${{ matrix.service }}/proto

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./test/${{ matrix.service }}
          file: ./test/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ matrix.service }}/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
