apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - grafana-certificate.yaml
  - grafana-httproute.yaml
  - grafana-healthcheck.yaml
  - cluster-issuer.yaml
    
# naming patches not to target
patches:
  - path: grafana-route-patch.yaml
  - path: grafana-certificate-patch.yaml
